### ISSUE TITLE
mk_apt: mk_apt_hook should not be deployed when checkmkagent_mk_apt_delay is not set

### ISSUE THREAD

**Issue by jkirk** [jkirk/ansible-role-checkmkagent#11]
Needs to be fixed like this:

```
- name: Deploy mk_apt_hook for usage with checkmk agent plugin mk_apt
  copy:            
    src: 'check-mk/mk_apt_hook'
    dest: '/etc/apt/apt.conf.d/98mk-apt'
    mode: 0644     
    owner: root    
    group: root 
  when:           
    - checkmkagent_mk_apt_delay is defined
    - checkmkagent_mk_apt_delay > 0
```

The `*mk_apt.cache` needs to be removed manually (if `checkmkagent_mk_apt_delay` is not set):

```
% ls -la /var/lib/check_mk_agent/cache
total 8
drwxr-xr-x 2 root root 4096 Dec 12 11:20  .
drwxr-xr-x 6 root root 4096 Dec 12 11:06  ..
-rw-r--r-- 1 root root    0 Dec 18  1970 '*mk_apt.cache'
```
